name: Deploy Documentation

on:
  push:
    branches:
      - main
      - master
      - 02-correcao-qlearning
      - sonar-cube-duplicated-lines

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
